version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    command: run-dev
    volumes:
      - ./api/src/:/api/src/
    environment:
      - MONGODB_URL=mongodb://user:passwd@mongo:27017
    ports:
      - 8080:80
  mongo:
    image: mongo:bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: passwd
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8002:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: user
        ME_CONFIG_MONGODB_ADMINPASSWORD: passwd
        ME_CONFIG_MONGODB_URL: mongodb://user:passwd@mongo:27017/

volumes:
  mongodbdata: